# Generated by Django 4.2.6 on 2023-11-18 15:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuento',
            name='text',
            field=ckeditor.fields.RichTextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='poema',
            name='text',
            field=ckeditor.fields.RichTextField(max_length=5000),
        ),
    ]
