# Generated by Django 4.2.6 on 2023-11-18 17:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_cuento_text_alter_poema_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=50)),
                ('text', ckeditor.fields.RichTextField(max_length=5000)),
                ('post', models.IntegerField(choices=[(1, 'Story'), (2, 'Poem')], default=1)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
