# Generated by Django 4.2.6 on 2023-11-18 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cuento',
        ),
        migrations.DeleteModel(
            name='Poema',
        ),
    ]
